# config/settings.yml
plugins:
  auth_no_email_enabled:
    default: true
    client: true
description: Enable to skip email verification during user registration. Users will be automatically activated.
